version: '3'
services:
  postgres:
    image: postgres:9.4
    restart: always
    container_name: 'matkollen'
    env_file: ./containerConfig/psql.env
    ports:
      - 5432:5432
    volumes:
      - ./containerConfig/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ./data/psql:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 1234:8080