
spring:
  datasource:
    url: ${AZURE_CONN_STRING}
    username: ${AZURE_USERNAME}
    password: ${AZURE_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  sql:
    init:
      platform: postgresql
      mode: always
    output:
      ansi:
        enabled: always

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR